"""Add date_created to ad_request

Revision ID: 6b510021b7bd
Revises: 18f7c3834b13
Create Date: 2024-07-21 00:15:53.937850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b510021b7bd'
down_revision = '18f7c3834b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=False))
        batch_op.alter_column('requirements',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('messages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messages', sa.TEXT(), nullable=True))
        batch_op.alter_column('requirements',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
